package com.thalesgroup.config.scdm.extract;

import java.util.Date;

/******************************************************************************/
/*  FILE  : WriterUtility.java                                                */
/*----------------------------------------------------------------------------*/
/*  COMPANY  : THALES TRANSPORTATION SYSTEM                                   */
/*  CREATION DATE : 10 juil. 07                                               */
/*  LANGUAGE  : JAVA                                                          */
/*............................................................................*/
/*  Copyright © THALES Transportation System 1996-2006.                       */
/*  All rights reserved.                                                      */
/*  Unauthorized access, use, reproduction or distribution is prohibited.     */
/******************************************************************************/


public class WriterUtility {

	static public final void writeHeader(ByteArrayWriter writer, String fileName) {
		// 65 * #
		writer.println("#################################################################");
		writer.println("###       THALES TRANSPORTATION SYSTEM - SCADAsoft            ###");
		writer.println("###                                                           ###");
		
		writer.print("###  File : ");
		writer.print(fileName);
		int length = 65 - 12 - fileName.length() - 3;
		for(int i=0; i<length; i++) {
			writer.print(" ");
		}
		writer.println("###");
		
		String date = new Date().toString();
		writer.print("###  Date : ");
		writer.print(date);
		length = 65 - 12 - date.length() - 3;
		for(int i=0; i<length; i++) {
			writer.print(" ");
		}
		writer.println("###");
		
		writer.println("###                                                           ###");
		writer.println("### This file is generated by the SCADAsoft SCDM Configurator ###");
		writer.println("#################################################################");
		writer.println();
	}
	
}
