@ECHO OFF

@EXIT /B 0

:LOG
	@SETLOCAL
	@SET TAG=[%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2% %TIME:~0,2%:%TIME:~3,2%:%TIME:~6,2% %~n0]
	@CALL :TEE %TAG% %*
	@ENDLOCAL
	@EXIT /B 0

:TEE
	@SETLOCAL
	@SET LOGFILE=%~n0.log
	@ECHO %*
	@ECHO %* >> "%LOGFILE%"
	@ENDLOCAL
	@EXIT /B 0

:PAUSE_IF_NOT_INTERACTIVE
	@SETLOCAL
	@IF DEFINED NOT_INTERACTIVE @EXIT /B 0
	@ECHO %CMDCMDLINE% | FINDSTR /L %COMSPEC% >NUL 2>&1
	@IF NOT %ERRORLEVEL% == 0 PAUSE
	@ENDLOCAL
	@EXIT /B 0

:STRLEN
	@SETLOCAL ENABLEDELAYEDEXPANSION
	@SET STR=%1
	@SET /A LEN=0
	:STRLEN_LOOP
		@IF NOT "!STR:~%LEN%!" == "" (
			@SET /A LEN+=1
			@GOTO :STRLEN_LOOP
		)
	@EXIT /B %LEN%
	@ENDLOCAL

:STRCMP
	@REM CALL :STRCMP SEARCH_TEXT IN_TEXT
	@SETLOCAL ENABLEDELAYEDEXPANSION
	@SET SEARCH_TEXT=%1
	@SET IN_TEXT=%2
	@CALL SET MATCHED=%%IN_TEXT:%SEARCH_TEXT%=%%
	@IF NOT x%MATCHED%==x%IN_TEXT% (
		@EXIT /B 1
	) ELSE (
		@EXIT /B 0
	)
	@ENDLOCAL

