@ECHO OFF

@REM ###########################################################################
@REM Parameters to specified per user environment
@REM ###########################################################################

@REM Path to Python executable, can be override by environment variable
IF NOT DEFINED PYTHON_BIN (
	SET PYTHON_BIN=C:\softs\Python27\python.exe
)

@REM "situationView" directory generated by MetaConfigurator, can be override by environment variable
@REM (e.g., <XXX>\widgets\situationView)
IF NOT DEFINED SITUATIONVIEW_DIR (
	SET SITUATIONVIEW_DIR=C:\SCSTraining\devconf\genhmi\widgets\situationView
)

@REM Symbol to SVG Mapping logic
SET SYM_TO_SVG_POINT_MGMT_MAP_LOGIC=%~dp0\logic_sym_to_svg_point_mgmt.bat
SET SYM_TO_SVG_POINT_MGMT_MAP_SPECIFIC_PATTERN=logic_sym_to_svg_point_mgmt_*.bat
SET SYM_TO_SVG_HIGHLIGHT_MAP_LOGIC=%~dp0\logic_sym_to_svg_highlight.bat
SET SYM_TO_SVG_HIGHLIGHT_MAP_SPECIFIC_PATTERN=logic_sym_to_svg_highlight_*.bat
SET SYM_BLINK_BLACKLIST_LOGIC=%~dp0\logic_sym_blink.bat

@REM Width, in pixel, of the HMI schematics display area, in pixel
SET SCHEMATIC_DISPLAY_WIDTH_PX=1596

@REM Height, in pixel, of the HMI schematics display area, in pixel
SET SCHEMATIC_DISPLAY_HEIGHT_PX=815

@REM Zoom levels, separated by space, of the schematics
@REM (e.g., 1x zoom: 1, 1.5x zoom: 1.5, 2x zoom: 2, etc)
SET SCHEMATIC_ZOOM_LEVELS=1 1.2 1.44 1.728 2.0736 2.48832 2.985984 3.5831808 4.29981696 5.159780352
